triggers:
- envs: []
  last_enabled_at: null
  name: cycle data central 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-07 16:30:00
  status: inactive
  variables:
    programme: Central
    year: 2019
- envs: []
  last_enabled_at: null
  name: cycle data central 2020
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 10:04:00
  status: inactive
  variables:
    programme: Central
    year: 2020
- envs: []
  last_enabled_at: null
  name: cycle data inner 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-07 16:29:00
  status: inactive
  variables:
    programme: Inner
    year: 2019
- envs: []
  last_enabled_at: null
  name: cycle data outer 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-07 16:23:00
  status: inactive
  variables:
    programme: Outer
    year: 2019
- envs: []
  last_enabled_at: 2024-04-13 17:18:42.061013
  name: cycle data inner 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:18:00
  status: inactive
  variables:
    programme: Inner
    year: 2018
- envs: []
  last_enabled_at: 2024-04-13 16:46:50.754182
  name: cycle data central 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 16:47:00
  status: inactive
  variables:
    programme: Central
    year: 2018
- envs: []
  last_enabled_at: null
  name: cycle data central 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 16:48:00
  status: inactive
  variables:
    programme: Central
    year: 2017
- envs: []
  last_enabled_at: 2024-04-13 17:20:53.767917
  name: cycle data outer 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:20:00
  status: inactive
  variables:
    programme: Outer
    year: 2018
- envs: []
  last_enabled_at: 2024-04-13 17:29:33.450046
  name: cycle data inner 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:28:00
  status: inactive
  variables:
    programme: Inner
    year: 2017
- envs: []
  last_enabled_at: 2024-04-13 17:33:23.851528+00:00
  name: cycle data outer 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:32:00
  status: active
  variables:
    programme: Outer
    year: 2017
