triggers:
- envs: []
  last_enabled_at: null
  name: cycle data central 2020
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 10:04:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Central
    project_id: go-de-zoomcamp-project-2024
    year: 2020
- envs: []
  last_enabled_at: null
  name: cycle data inner 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-07 16:29:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Inner
    project_id: go-de-zoomcamp-project-2024
    year: 2019
- envs: []
  last_enabled_at: null
  name: cycle data outer 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-07 16:23:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Outer
    project_id: go-de-zoomcamp-project-2024
    year: 2019
- envs: []
  last_enabled_at: 2024-04-14 15:16:30.512644
  name: cycle data inner 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:18:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Inner
    project_id: go-de-zoomcamp-project-2024
    year: 2018
- envs: []
  last_enabled_at: 2024-04-13 16:46:50.754182
  name: cycle data central 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 16:47:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Central
    project_id: go-de-zoomcamp-project-2024
    year: 2018
- envs: []
  last_enabled_at: 2024-04-14 13:34:49.655608
  name: cycle data central 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 16:48:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Central
    project_id: go-de-zoomcamp-project-2024
    year: 2017
- envs: []
  last_enabled_at: 2024-04-13 17:20:53.767917
  name: cycle data outer 2018
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:20:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Outer
    project_id: go-de-zoomcamp-project-2024
    year: 2018
- envs: []
  last_enabled_at: 2024-04-13 17:29:33.450046
  name: cycle data inner 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:28:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Inner
    project_id: go-de-zoomcamp-project-2024
    year: 2017
- envs: []
  last_enabled_at: 2024-04-13 17:33:23.851528
  name: cycle data outer 2017
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-13 17:32:00
  status: inactive
  variables:
    bucket_name: go-de-zoomcamp-project-2024-bucket
    dataset: london_cycles
    google_app_cred_location: /home/src/keys/go-de-zoomcamp-project-2024.json
    programme: Outer
    project_id: go-de-zoomcamp-project-2024
    year: 2017
- envs: []
  last_enabled_at: null
  name: cycle data central 2019
  pipeline_uuid: cycles_data_pipeline
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-14 13:10:00
  status: inactive
  variables: {}
