version: 2

sources:
  - name: staging
    database: go-de-zoomcamp-project-2024
    schema: london_cycles

      # loaded_at_field: record_loaded_at
    tables:
      - name: Central_cycle_data
      - name: Inner_cycle_data
      - name: Outer_cycle_data

models:
  - name: stg_central_cycle_data
    description: ""
    columns:
      - name: cycle_id
        data_type: string
        description: ""
        #tests:
        #    - unique:
        #        severity: warn
        #    - not_null:
        #        severity: warn

      - name: date_time
        data_type: datetime
        description: ""

      - name: year
        data_type: string
        description: ""

      - name: locationid
        data_type: string
        description: ""

      - name: weather
        data_type: string
        description: ""

      - name: day
        data_type: string
        description: ""

      - name: round
        data_type: string
        description: ""

      - name: dir
        data_type: string
        description: ""

      - name: path
        data_type: string
        description: ""

      - name: mode
        data_type: string
        description: ""

      - name: count
        data_type: int64
        description: ""

      - name: programme
        data_type: string
        description: ""
